#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RoleDescriptor {
    pub index: usize,
    pub group: &'static str,
    pub name: &'static str,
    pub description: &'static str,
}

pub const ROLES: [RoleDescriptor; 50] = [
    RoleDescriptor {
        index: 0,
        group: "theme-designer-group-wall",
        name: "theme-designer-role-accent",
        description: "theme-designer-role-accent-desc",
    },
    RoleDescriptor {
        index: 1,
        group: "theme-designer-group-wall",
        name: "theme-designer-role-accent-text",
        description: "theme-designer-role-accent-text-desc",
    },
    RoleDescriptor {
        index: 2,
        group: "theme-designer-group-wall",
        name: "theme-designer-role-second-accent",
        description: "theme-designer-role-second-accent-desc",
    },
    RoleDescriptor {
        index: 3,
        group: "theme-designer-group-wall",
        name: "theme-designer-role-panel",
        description: "theme-designer-role-panel-desc",
    },
    RoleDescriptor {
        index: 4,
        group: "theme-designer-group-wall",
        name: "theme-designer-role-panel-text",
        description: "theme-designer-role-panel-text-desc",
    },
    RoleDescriptor {
        index: 5,
        group: "theme-designer-group-wall",
        name: "theme-designer-role-panel-alt",
        description: "theme-designer-role-panel-alt-desc",
    },
    RoleDescriptor {
        index: 6,
        group: "theme-designer-group-wall",
        name: "theme-designer-role-panel-raised",
        description: "theme-designer-role-panel-raised-desc",
    },
    RoleDescriptor {
        index: 7,
        group: "theme-designer-group-wall",
        name: "theme-designer-role-backdrop",
        description: "theme-designer-role-backdrop-desc",
    },
    RoleDescriptor {
        index: 8,
        group: "theme-designer-group-wall",
        name: "theme-designer-role-outline",
        description: "theme-designer-role-outline-desc",
    },
    RoleDescriptor {
        index: 9,
        group: "theme-designer-group-error",
        name: "theme-designer-role-error",
        description: "theme-designer-role-error-desc",
    },
    RoleDescriptor {
        index: 10,
        group: "theme-designer-group-error",
        name: "theme-designer-role-error-container",
        description: "theme-designer-role-error-container-desc",
    },
    RoleDescriptor {
        index: 11,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-inverse-on-surface",
        description: "theme-designer-role-inverse-on-surface-desc",
    },
    RoleDescriptor {
        index: 12,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-inverse-primary",
        description: "theme-designer-role-inverse-primary-desc",
    },
    RoleDescriptor {
        index: 13,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-inverse-surface",
        description: "theme-designer-role-inverse-surface-desc",
    },
    RoleDescriptor {
        index: 14,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-on-background",
        description: "theme-designer-role-on-background-desc",
    },
    RoleDescriptor {
        index: 15,
        group: "theme-designer-group-error",
        name: "theme-designer-role-on-error",
        description: "theme-designer-role-on-error-desc",
    },
    RoleDescriptor {
        index: 16,
        group: "theme-designer-group-error",
        name: "theme-designer-role-on-error-container",
        description: "theme-designer-role-on-error-container-desc",
    },
    RoleDescriptor {
        index: 17,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-on-primary-container",
        description: "theme-designer-role-on-primary-container-desc",
    },
    RoleDescriptor {
        index: 18,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-on-primary-fixed",
        description: "theme-designer-role-on-primary-fixed-desc",
    },
    RoleDescriptor {
        index: 19,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-on-primary-fixed-variant",
        description: "theme-designer-role-on-primary-fixed-variant-desc",
    },
    RoleDescriptor {
        index: 20,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-on-secondary",
        description: "theme-designer-role-on-secondary-desc",
    },
    RoleDescriptor {
        index: 21,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-on-secondary-container",
        description: "theme-designer-role-on-secondary-container-desc",
    },
    RoleDescriptor {
        index: 22,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-on-secondary-fixed",
        description: "theme-designer-role-on-secondary-fixed-desc",
    },
    RoleDescriptor {
        index: 23,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-on-secondary-fixed-variant",
        description: "theme-designer-role-on-secondary-fixed-variant-desc",
    },
    RoleDescriptor {
        index: 24,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-on-surface-variant",
        description: "theme-designer-role-on-surface-variant-desc",
    },
    RoleDescriptor {
        index: 25,
        group: "theme-designer-group-tertiary",
        name: "theme-designer-role-on-tertiary",
        description: "theme-designer-role-on-tertiary-desc",
    },
    RoleDescriptor {
        index: 26,
        group: "theme-designer-group-tertiary",
        name: "theme-designer-role-on-tertiary-container",
        description: "theme-designer-role-on-tertiary-container-desc",
    },
    RoleDescriptor {
        index: 27,
        group: "theme-designer-group-tertiary",
        name: "theme-designer-role-on-tertiary-fixed",
        description: "theme-designer-role-on-tertiary-fixed-desc",
    },
    RoleDescriptor {
        index: 28,
        group: "theme-designer-group-tertiary",
        name: "theme-designer-role-on-tertiary-fixed-variant",
        description: "theme-designer-role-on-tertiary-fixed-variant-desc",
    },
    RoleDescriptor {
        index: 29,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-outline-variant",
        description: "theme-designer-role-outline-variant-desc",
    },
    RoleDescriptor {
        index: 30,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-primary-container",
        description: "theme-designer-role-primary-container-desc",
    },
    RoleDescriptor {
        index: 31,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-primary-fixed",
        description: "theme-designer-role-primary-fixed-desc",
    },
    RoleDescriptor {
        index: 32,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-primary-fixed-dim",
        description: "theme-designer-role-primary-fixed-dim-desc",
    },
    RoleDescriptor {
        index: 33,
        group: "theme-designer-group-effects",
        name: "theme-designer-role-scrim",
        description: "theme-designer-role-scrim-desc",
    },
    RoleDescriptor {
        index: 34,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-secondary",
        description: "theme-designer-role-secondary-desc",
    },
    RoleDescriptor {
        index: 35,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-secondary-container",
        description: "theme-designer-role-secondary-container-desc",
    },
    RoleDescriptor {
        index: 36,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-secondary-fixed",
        description: "theme-designer-role-secondary-fixed-desc",
    },
    RoleDescriptor {
        index: 37,
        group: "theme-designer-group-accents",
        name: "theme-designer-role-secondary-fixed-dim",
        description: "theme-designer-role-secondary-fixed-dim-desc",
    },
    RoleDescriptor {
        index: 38,
        group: "theme-designer-group-effects",
        name: "theme-designer-role-shadow",
        description: "theme-designer-role-shadow-desc",
    },
    RoleDescriptor {
        index: 39,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-surface-bright",
        description: "theme-designer-role-surface-bright-desc",
    },
    RoleDescriptor {
        index: 40,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-surface-container-high",
        description: "theme-designer-role-surface-container-high-desc",
    },
    RoleDescriptor {
        index: 41,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-surface-container-highest",
        description: "theme-designer-role-surface-container-highest-desc",
    },
    RoleDescriptor {
        index: 42,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-surface-container-low",
        description: "theme-designer-role-surface-container-low-desc",
    },
    RoleDescriptor {
        index: 43,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-surface-container-lowest",
        description: "theme-designer-role-surface-container-lowest-desc",
    },
    RoleDescriptor {
        index: 44,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-surface-dim",
        description: "theme-designer-role-surface-dim-desc",
    },
    RoleDescriptor {
        index: 45,
        group: "theme-designer-group-surfaces",
        name: "theme-designer-role-surface-tint",
        description: "theme-designer-role-surface-tint-desc",
    },
    RoleDescriptor {
        index: 46,
        group: "theme-designer-group-tertiary",
        name: "theme-designer-role-tertiary-container",
        description: "theme-designer-role-tertiary-container-desc",
    },
    RoleDescriptor {
        index: 47,
        group: "theme-designer-group-tertiary",
        name: "theme-designer-role-tertiary-fixed",
        description: "theme-designer-role-tertiary-fixed-desc",
    },
    RoleDescriptor {
        index: 48,
        group: "theme-designer-group-tertiary",
        name: "theme-designer-role-tertiary-fixed-dim",
        description: "theme-designer-role-tertiary-fixed-dim-desc",
    },
    RoleDescriptor {
        index: 49,
        group: "theme-designer-group-effects",
        name: "theme-designer-role-source-color",
        description: "theme-designer-role-source-color-desc",
    },
];
